// #region Generated code
// <!-- generated:start -->
// This section is automatically generated by the 'build:source' script, any change will be overwritten

import Arcane from './Lists/Arcane'
import AstroBotList from './Lists/AstroBotList'
import BladeBotList from './Lists/BladeBotList'
import Blist from './Lists/Blist'
import BotListSpace from './Lists/BotListSpace'
import BotsDataBase from './Lists/BotsDataBase'
import BotsForDiscord from './Lists/BotsForDiscord'
import BotsOnDiscord from './Lists/BotsOnDiscord'
import Carbon from './Lists/Carbon'
import DBots from './Lists/DBots'
import DiscordAppsDev from './Lists/DiscordAppsDev'
import DiscordBoats from './Lists/DiscordBoats'
import DiscordBotDirectory from './Lists/DiscordBotDirectory'
import DiscordBotList from './Lists/DiscordBotList'
import DiscordBotsCo from './Lists/DiscordBotsCo'
import DiscordBotsGG from './Lists/DiscordBotsGG'
import DiscordExtremeList from './Lists/DiscordExtremeList'
import DiscordLabs from './Lists/DiscordLabs'
import DiscordListology from './Lists/DiscordListology'
import DiscordServices from './Lists/DiscordServices'
import Disforge from './Lists/Disforge'
import FatesList from './Lists/FatesList'
import GlennBotList from './Lists/GlennBotList'
import InfinityBotList from './Lists/InfinityBotList'
import ListMyBots from './Lists/ListMyBots'
import ParadiseBots from './Lists/ParadiseBots'
import SpaceBotsList from './Lists/SpaceBotsList'
import TopCord from './Lists/TopCord'
import TopGG from './Lists/TopGG'
import VoidBots from './Lists/VoidBots'
import WonderBotList from './Lists/WonderBotList'
import YABL from './Lists/YABL'

// prettier-ignore
export const serviceList = {
  'arcane': Arcane,
  'arcane-center.xyz': Arcane,
  'astrobotlist': AstroBotList,
  'botlists.com': AstroBotList,
  'bladebotlist': BladeBotList,
  'bladebotlist.xyz': BladeBotList,
  'blist': Blist,
  'blist.xyz': Blist,
  'botlistspace': BotListSpace,
  'botlist.space': BotListSpace,
  'botsdatabase': BotsDataBase,
  'botsdatabase.com': BotsDataBase,
  'botsfordiscord': BotsForDiscord,
  'botsfordiscord.com': BotsForDiscord,
  'botsondiscord': BotsOnDiscord,
  'bots.ondiscord.xyz': BotsOnDiscord,
  'carbonitex': Carbon,
  'carbonitex.net': Carbon,
  'carbon': Carbon,
  'dbots': DBots,
  'dbots.co': DBots,
  'discordappsdev': DiscordAppsDev,
  'discordapps.dev': DiscordAppsDev,
  'discordboats': DiscordBoats,
  'discord.boats': DiscordBoats,
  'discordbotdirectory': DiscordBotDirectory,
  'discordbotdirectory.net': DiscordBotDirectory,
  'discordbotlist': DiscordBotList,
  'discordbotlist.com': DiscordBotList,
  'discordbotsco': DiscordBotsCo,
  'discordbots.co': DiscordBotsCo,
  'discordbotsgg': DiscordBotsGG,
  'discord.bots.gg': DiscordBotsGG,
  'discordextremelist': DiscordExtremeList,
  'discordextremelist.xyz': DiscordExtremeList,
  'discordlabs': DiscordLabs,
  'discordlabs.org': DiscordLabs,
  'discordlistology': DiscordListology,
  'discordlistology.com': DiscordListology,
  'discordservices': DiscordServices,
  'discordservices.net': DiscordServices,
  'disforge': Disforge,
  'disforge.com': Disforge,
  'fateslist': FatesList,
  'fateslist.xyz': FatesList,
  'glennbotlist': GlennBotList,
  'glennbotlist.xyz': GlennBotList,
  'infinitybotlist': InfinityBotList,
  'infinitybotlist.com': InfinityBotList,
  'listmybots': ListMyBots,
  'listmybots.com': ListMyBots,
  'paradisebots': ParadiseBots,
  'paradisebots.net': ParadiseBots,
  'spacebotslist': SpaceBotsList,
  'space-bot-list.xyz': SpaceBotsList,
  'topcord': TopCord,
  'topcord.xyz': TopCord,
  'topgg': TopGG,
  'top.gg': TopGG,
  'voidbots': VoidBots,
  'voidbots.net': VoidBots,
  'wonderbotlist': WonderBotList,
  'wonderbotlist.com': WonderBotList,
  'yabl': YABL,
  'yabl.xyz': YABL,
}
// <!-- generated:end -->
// #endregion
