// #region Generated code
// <!-- generated:start -->
// This section is automatically generated by the 'build:source' script, any change will be overwritten

import BladeList from './Lists/BladeList'
import Blist from './Lists/Blist'
import BotsOnDiscord from './Lists/BotsOnDiscord'
import Carbon from './Lists/Carbon'
import DBots from './Lists/DBots'
import DiscordBoats from './Lists/DiscordBoats'
import DiscordBotList from './Lists/DiscordBotList'
import DiscordBotlistEU from './Lists/DiscordBotlistEU'
import DiscordBotsGG from './Lists/DiscordBotsGG'
import DiscordExtremeList from './Lists/DiscordExtremeList'
import DiscordLabs from './Lists/DiscordLabs'
import DiscordListology from './Lists/DiscordListology'
import DiscordListSpace from './Lists/DiscordListSpace'
import DiscordsCom from './Lists/DiscordsCom'
import DiscordServices from './Lists/DiscordServices'
import Disforge from './Lists/Disforge'
import FatesList from './Lists/FatesList'
import GlennBotList from './Lists/GlennBotList'
import InfinityBotList from './Lists/InfinityBotList'
import Listcord from './Lists/Listcord'
import MotionBotList from './Lists/MotionBotList'
import SpaceBotsList from './Lists/SpaceBotsList'
import TopCord from './Lists/TopCord'
import TopGG from './Lists/TopGG'
import VoidBots from './Lists/VoidBots'
import WonderBotList from './Lists/WonderBotList'
import YABL from './Lists/YABL'

// prettier-ignore
export const serviceList = {
  'bladebotlist': BladeList,
  'bladebotlist.xyz': BladeList,
  'bladelist': BladeList,
  'bladelist.gg': BladeList,
  'blist': Blist,
  'blist.xyz': Blist,
  'botsondiscord': BotsOnDiscord,
  'bots.ondiscord.xyz': BotsOnDiscord,
  'carbonitex': Carbon,
  'carbonitex.net': Carbon,
  'carbon': Carbon,
  'dbots': DBots,
  'dbots.co': DBots,
  'discordboats': DiscordBoats,
  'discord.boats': DiscordBoats,
  'discordbotlist': DiscordBotList,
  'discordbotlist.com': DiscordBotList,
  'dbleu': DiscordBotlistEU,
  'discordbotlisteu': DiscordBotlistEU,
  'discordbotsgg': DiscordBotsGG,
  'discord.bots.gg': DiscordBotsGG,
  'discordextremelist': DiscordExtremeList,
  'discordextremelist.xyz': DiscordExtremeList,
  'discordlabs': DiscordLabs,
  'discordlabs.org': DiscordLabs,
  'discordlistology': DiscordListology,
  'discordlistology.com': DiscordListology,
  'discordlistspace': DiscordListSpace,
  'discordlist.space': DiscordListSpace,
  'botlistspace': DiscordListSpace,
  'botlist.space': DiscordListSpace,
  'botsfordiscord': DiscordsCom,
  'botsfordiscord.com': DiscordsCom,
  'discords': DiscordsCom,
  'discords.com': DiscordsCom,
  'discordservices': DiscordServices,
  'discordservices.net': DiscordServices,
  'disforge': Disforge,
  'disforge.com': Disforge,
  'fateslist': FatesList,
  'fateslist.xyz': FatesList,
  'glennbotlist': GlennBotList,
  'glennbotlist.xyz': GlennBotList,
  'infinitybotlist': InfinityBotList,
  'infinitybotlist.com': InfinityBotList,
  'listcord': Listcord,
  'listcord.gg': Listcord,
  'motion': MotionBotList,
  'motiondevelopment': MotionBotList,
  'motionbotlist': MotionBotList,
  'motiondevelopment.top': MotionBotList,
  'spacebotslist': SpaceBotsList,
  'space-bot-list.xyz': SpaceBotsList,
  'topcord': TopCord,
  'topcord.xyz': TopCord,
  'topgg': TopGG,
  'top.gg': TopGG,
  'voidbots': VoidBots,
  'voidbots.net': VoidBots,
  'wonderbotlist': WonderBotList,
  'wonderbotlist.com': WonderBotList,
  'yabl': YABL,
  'yabl.xyz': YABL,
}
// <!-- generated:end -->
// #endregion
