// #region Generated code
// <!-- generated:start -->
// This section is automatically generated by the 'build:source' script, any change will be overwritten

import BotlistMe from './Lists/BotlistMe'
import BotsOnDiscord from './Lists/BotsOnDiscord'
import Carbon from './Lists/Carbon'
import DList from './Lists/DList'
import DiscordBotList from './Lists/DiscordBotList'
import DiscordBotsGG from './Lists/DiscordBotsGG'
import DiscordExtremeList from './Lists/DiscordExtremeList'
import DiscordServices from './Lists/DiscordServices'
import DiscordsCom from './Lists/DiscordsCom'
import Disforge from './Lists/Disforge'
import InfinityBotList from './Lists/InfinityBotList'
import Radarcord from './Lists/Radarcord'
import TopGG from './Lists/TopGG'
import VoidBots from './Lists/VoidBots'
import YABL from './Lists/YABL'

// prettier-ignore
export const serviceList = {
  'botlistme': BotlistMe,
  'botlist.me': BotlistMe,
  'botsondiscord': BotsOnDiscord,
  'bots.ondiscord.xyz': BotsOnDiscord,
  'carbonitex': Carbon,
  'carbonitex.net': Carbon,
  'carbon': Carbon,
  'dlistgg': DList,
  'dlist.gg': DList,
  'discordlistgg': DList,
  'discordlist.gg': DList,
  'discordbotlist': DiscordBotList,
  'discordbotlist.com': DiscordBotList,
  'discordbotsgg': DiscordBotsGG,
  'discord.bots.gg': DiscordBotsGG,
  'discordextremelist': DiscordExtremeList,
  'discordextremelist.xyz': DiscordExtremeList,
  'discordservices': DiscordServices,
  'discordservices.net': DiscordServices,
  'botsfordiscord': DiscordsCom,
  'botsfordiscord.com': DiscordsCom,
  'discords': DiscordsCom,
  'discords.com': DiscordsCom,
  'disforge': Disforge,
  'disforge.com': Disforge,
  'infinitybotlist': InfinityBotList,
  'infinitybotlist.com': InfinityBotList,
  'infinitybots': InfinityBotList,
  'infinitybots.gg': InfinityBotList,
  'radar': Radarcord,
  'radarbots': Radarcord,
  'radarbotdirectory.xyz': Radarcord,
  'radarcord': Radarcord,
  'radarcord.net': Radarcord,
  'topgg': TopGG,
  'top.gg': TopGG,
  'voidbots': VoidBots,
  'voidbots.net': VoidBots,
  'yabl': YABL,
  'yabl.xyz': YABL,
}
// <!-- generated:end -->
// #endregion
