name: Deployment
on:
  push:
    branches:
      - '*'
      - '!docs'
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/deployment.yml'
      - 'scripts/docs.js'
      - 'scripts/post-docgen.js'
      - 'package.json'
      - 'README.md'
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs

      - name: Deploy documentation
        uses: dbots-pkg/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docs in repo
        uses: EndBug/add-and-commit@v4
        with:
          add: docs/*.md
          message: '[auto] docs: update docs'
