name: Docs
on:
  push:
    branches:
      - '*'
      - '!docs'
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs

      - name: Deploy documentation
        uses: dbots-pkg/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docs in repo
        uses: EndBug/add-and-commit@v4
        with:
          add: docs/*.md
          message: '[auto] docs: update docs'
