name: Test
on:
  push:
    branches:
      - "*"
      - "!docs"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Jest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Run tests
        run: npm run test:cov

      - name: Upload coverage result to CodeCov
        run: bash <(curl -s https://codecov.io/bash)

  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint

  webpack:
    name: Run webpack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run webpack

